name: build

on: [push, create, pull_request]

jobs:
  build_matrix:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
          - "ubuntu-latest"
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec

  build:
    needs: [build_matrix]
    runs-on: ubuntu-24.04
    steps:
      - name: Dummy for branch status checks
        run: |
          echo "build complete"

  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04

    needs:
      - build

    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: PUMA, ${{ vars.RUBYGEMS_SECRET_ARN }}
          parse-json-secrets: true

      - name: Create credentials
        run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${{ env.PUMA_RUBYGEMS_TOKEN  }}
          EOF
          chmod 0600 /home/runner/.gem/credentials

      - name: Publish gem
        run: |
          gem build puma-plugin-telemetry_too.gemspec
          gem push puma-plugin-telemetry_too-*.gem
