name: build

on: [push, create, pull_request]

jobs:
  build_matrix:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
          - "ubuntu-latest"
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec

  build:
    needs: [build_matrix]
    runs-on: ubuntu-24.04
    steps:
      - name: Dummy for branch status checks
        run: |
          echo "build complete"

  release:
    needs: build
    runs-on: ubuntu-24.04

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    # GitHub environment configured on RubyGems.org
    environment: release

    steps:
      # Set up
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Push new gem version to RubyGems.org
      - uses: rubygems/release-gem@v1
