---
name: Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
          - "ubuntu-latest"
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec
